<a href="https://colab.research.google.com/github/Yiding5805/Econnometrics_2021/blob/main/M5_Active.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

Story Background: https://www.gemini.com/cryptopedia/the-dao-hack-makerdao

Event: July 20, 2016, at block 192,000

[Data Metrics](https://github.com/coinmetrics-io/data/blob/master/csv/metrics.csv)

In [ ]:
import pandas as pd
import numpy as np

###import the data for Ethereum

In [ ]:
df_eth=pd.read_csv("https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/eth.csv")
df_eth.head()

         time  AdrActCnt  ...  VtyDayRet180d  VtyDayRet30d
0  2015-07-30     9206.0  ...            NaN           NaN
1  2015-07-31      424.0  ...            NaN           NaN
2  2015-08-01      413.0  ...            NaN           NaN
3  2015-08-02      432.0  ...            NaN           NaN
4  2015-08-03      444.0  ...            NaN           NaN

[5 rows x 139 columns]

In [ ]:
df_eth['time']=pd.to_datetime(df_eth['time'])
df_eth.dtypes

time                datetime64[ns]
AdrActCnt                  float64
AdrBal1in100KCnt           float64
AdrBal1in100MCnt           float64
AdrBal1in10BCnt            float64
                         ...
TxTfrValMedNtv             float64
TxTfrValMedUSD             float64
VelCur1yr                  float64
VtyDayRet180d              float64
VtyDayRet30d               float64
Length: 139, dtype: object

In [ ]:
df_eth['Type'] = 'eth'
df_eth.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet180d  VtyDayRet30d  Type
0 2015-07-30     9206.0            5685.0  ...            NaN           NaN   eth
1 2015-07-31      424.0            5692.0  ...            NaN           NaN   eth
2 2015-08-01      413.0            5699.0  ...            NaN           NaN   eth
3 2015-08-02      432.0            5708.0  ...            NaN           NaN   eth
4 2015-08-03      444.0            5715.0  ...            NaN           NaN   eth

[5 rows x 140 columns]

### Import the Data for Ethereum Classic

In [ ]:
df_etc=pd.read_csv("https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/etc.csv")
df_etc.head()

         time  AdrActCnt  ...  VtyDayRet180d  VtyDayRet30d
0  2016-07-20    21680.0  ...            NaN           NaN
1  2016-07-21    17037.0  ...            NaN           NaN
2  2016-07-22    13208.0  ...            NaN           NaN
3  2016-07-23     9838.0  ...            NaN           NaN
4  2016-07-24    14910.0  ...            NaN           NaN

[5 rows x 134 columns]

In [ ]:
### change to dateime
df_etc['time']=pd.to_datetime(df_etc['time'])
df_etc.dtypes

time                datetime64[ns]
AdrActCnt                  float64
AdrBal1in100KCnt           float64
AdrBal1in100MCnt           float64
AdrBal1in10BCnt            float64
                         ...
TxTfrValMedNtv             float64
TxTfrValMedUSD             float64
VelCur1yr                  float64
VtyDayRet180d              float64
VtyDayRet30d               float64
Length: 134, dtype: object

In [ ]:
df_etc['Type'] = 'etc'
df_etc.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet180d  VtyDayRet30d  Type
0 2016-07-20    21680.0            5491.0  ...            NaN           NaN   etc
1 2016-07-21    17037.0            5471.0  ...            NaN           NaN   etc
2 2016-07-22    13208.0            5497.0  ...            NaN           NaN   etc
3 2016-07-23     9838.0            5499.0  ...            NaN           NaN   etc
4 2016-07-24    14910.0            5304.0  ...            NaN           NaN   etc

[5 rows x 135 columns]

# Regression Discontinguity

https://youtu.be/TfKwgGT2fSM

### create the identifier varaible for Dao Hack

In [ ]:
from datetime import date

In [ ]:
df_eth ['After_DaoHack'] =df_eth['time'].apply(lambda x: 1 if x>= date(2016,7,20) else 0)
df_eth[df_eth.time.dt.date>=date(2016,7,18)].head()

          time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet30d  Type  After_DaoHack
354 2016-07-18    18988.0            6564.0  ...      0.056129   eth              0
355 2016-07-19    26614.0            5492.0  ...      0.054430   eth              0
356 2016-07-20    25428.0            5730.0  ...      0.055036   eth              1
357 2016-07-21    22477.0            5866.0  ...      0.051285   eth              1
358 2016-07-22    24563.0            5917.0  ...      0.058285   eth              1

[5 rows x 141 columns]

In [ ]:
df_eth['days']=df_eth.index
df_eth.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  Type  After_DaoHack  days
0 2015-07-30     9206.0            5685.0  ...   eth              0     0
1 2015-07-31      424.0            5692.0  ...   eth              0     1
2 2015-08-01      413.0            5699.0  ...   eth              0     2
3 2015-08-02      432.0            5708.0  ...   eth              0     3
4 2015-08-03      444.0            5715.0  ...   eth              0     4

[5 rows x 142 columns]

### normalize the data

In [ ]:
df_eth['days'][df_eth.time.dt.date==date(2016,7,20)]

356    356
Name: days, dtype: int64

In [ ]:
df_eth['days']=df_eth['days']-356
df_eth[df_eth.time.dt.date>=date(2016,7,18)].head()

          time  AdrActCnt  AdrBal1in100KCnt  ...  Type  After_DaoHack  days
354 2016-07-18    18988.0            6564.0  ...   eth              0    -2
355 2016-07-19    26614.0            5492.0  ...   eth              0    -1
356 2016-07-20    25428.0            5730.0  ...   eth              1     0
357 2016-07-21    22477.0            5866.0  ...   eth              1     1
358 2016-07-22    24563.0            5917.0  ...   eth              1     2

[5 rows x 142 columns]

## create the regression function

https://www.statsmodels.org/stable/index.html

In [ ]:
 import statsmodels.api as sm
 import statsmodels.formula.api as smf

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
results = smf.ols('AdrActCnt ~ 1+ After_DaoHack +days+TxTfrValAdjUSD ', data=df_eth).fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              AdrActCnt   R-squared:                       0.293
Model:                            OLS   Adj. R-squared:                  0.292
Method:                 Least Squares   F-statistic:                     296.7
Date:                Fri, 25 Jun 2021   Prob (F-statistic):          4.50e-161
Time:                        05:26:40   Log-Likelihood:                -29882.
No. Observations:                2147   AIC:                         5.977e+04
Df Residuals:                    2143   BIC:                         5.979e+04
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       4.265e+04   1.46e+04      2.924      0.003     1.4e+04    7.13e+04
After_DaoHack   8.837e+04   2.06e+04      4.289      0.000     4.8e+04    1.29e+05
days             199.1747     13.207     15.082      0.000     173.276     225.074
TxTfrValAdjUSD   1.29e-05   1.59e-06      8.105      0.000    9.78e-06     1.6e-05
==============================================================================
Omnibus:                     4285.602   Durbin-Watson:                   0.484
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          9631932.640
Skew:                          15.814   Prob(JB):                         0.00
Kurtosis:                     329.603   Cond. No.                     1.78e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.78e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
results = smf.ols('AdrActCnt ~ 1+ After_DaoHack + days +After_DaoHack*days +TxTfrValAdjUSD', data=df_eth).fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              AdrActCnt   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                  0.292
Method:                 Least Squares   F-statistic:                     222.7
Date:                Fri, 25 Jun 2021   Prob (F-statistic):          5.49e-160
Time:                        05:26:40   Log-Likelihood:                -29881.
No. Observations:                2147   AIC:                         5.977e+04
Df Residuals:                    2142   BIC:                         5.980e+04
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept           1.959e+04   2.89e+04      0.678      0.498    -3.7e+04    7.62e+04
After_DaoHack       1.105e+05   3.16e+04      3.500      0.000    4.86e+04    1.72e+05
days                  66.6236    143.806      0.463      0.643    -215.390     348.637
After_DaoHack:days   133.6748    144.412      0.926      0.355    -149.528     416.877
TxTfrValAdjUSD      1.284e-05   1.59e-06      8.067      0.000    9.72e-06     1.6e-05
==============================================================================
Omnibus:                     4287.807   Durbin-Watson:                   0.484
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          9658614.841
Skew:                          15.832   Prob(JB):                         0.00
Kurtosis:                     330.055   Cond. No.                     3.10e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.1e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

# Difference in Difference

https://towardsdatascience.com/causal-inference-101-difference-in-differences-1fbbb0f55e85

### prepare the datasets

In [ ]:
Columns =["time","AdrActCnt","TxTfrValAdjUSD","FeeMedUSD","RevUSD","GasLmtTxMean","Type"]
df_eth =df_eth[Columns]
df_etc =df_etc[Columns]

In [ ]:
df_etc =df_etc.dropna()
df_etc.head()

        time  AdrActCnt  TxTfrValAdjUSD  ...         RevUSD   GasLmtTxMean  Type
5 2016-07-25    12384.0    3.988031e+06  ...   19053.076289  128512.450456   etc
6 2016-07-26    16696.0    2.138461e+07  ...  117166.149612  106473.058865   etc
7 2016-07-27    19134.0    1.597548e+07  ...   53581.634999  121838.776100   etc
8 2016-07-28    11646.0    2.210299e+07  ...   57859.069868  118155.032968   etc
9 2016-07-29     5873.0    1.257784e+07  ...   58069.745834  108353.172803   etc

[5 rows x 7 columns]

In [ ]:
df_eth =df_eth[df_eth.time.dt.date>=date(2016,7,25)]
df_etc =df_etc[df_etc.time.dt.date>=date(2016,7,25)]

In [ ]:
df_eth=df_eth.reset_index()
df_etc=df_etc.reset_index()

In [ ]:
df_eth["days"]=df_eth.index
df_eth.head()

   index       time  AdrActCnt  ...   GasLmtTxMean  Type  days
0    361 2016-07-25    25220.0  ...  116866.529623   eth     0
1    362 2016-07-26    30114.0  ...  106522.289666   eth     1
2    363 2016-07-27    28854.0  ...  126615.358103   eth     2
3    364 2016-07-28    24418.0  ...  133514.917908   eth     3
4    365 2016-07-29    23504.0  ...  139836.829202   eth     4

[5 rows x 9 columns]

In [ ]:
df_etc["days"]=df_etc.index
df_etc.head()

   index       time  AdrActCnt  ...   GasLmtTxMean  Type  days
0      5 2016-07-25    12384.0  ...  128512.450456   etc     0
1      6 2016-07-26    16696.0  ...  106473.058865   etc     1
2      7 2016-07-27    19134.0  ...  121838.776100   etc     2
3      8 2016-07-28    11646.0  ...  118155.032968   etc     3
4      9 2016-07-29     5873.0  ...  108353.172803   etc     4

[5 rows x 9 columns]

In [ ]:
df = pd.concat([df_eth, df_etc], axis=0)
df.head()

   index       time  AdrActCnt  ...   GasLmtTxMean  Type  days
0    361 2016-07-25    25220.0  ...  116866.529623   eth     0
1    362 2016-07-26    30114.0  ...  106522.289666   eth     1
2    363 2016-07-27    28854.0  ...  126615.358103   eth     2
3    364 2016-07-28    24418.0  ...  133514.917908   eth     3
4    365 2016-07-29    23504.0  ...  139836.829202   eth     4

[5 rows x 9 columns]

In [ ]:
df["etc"]=df["Type"].apply(lambda x: 1 if x=="etc" else 0)
df.head()

   index       time  AdrActCnt  TxTfrValAdjUSD  ...   GasLmtTxMean  Type  days etc
0    361 2016-07-25    25220.0    1.100270e+08  ...  116866.529623   eth     0   0
1    362 2016-07-26    30114.0    1.962552e+08  ...  106522.289666   eth     1   0
2    363 2016-07-27    28854.0    1.251180e+08  ...  126615.358103   eth     2   0
3    364 2016-07-28    24418.0    8.846049e+07  ...  133514.917908   eth     3   0
4    365 2016-07-29    23504.0    5.242804e+07  ...  139836.829202   eth     4   0

[5 rows x 10 columns]

### run the regression

Treatment: ETC hard-fork

In [ ]:
 import statsmodels.api as sm
 import statsmodels.formula.api as smf

In [ ]:
results = smf.ols('AdrActCnt ~ 1+ etc +days+TxTfrValAdjUSD+FeeMedUSD+RevUSD+GasLmtTxMean', data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              AdrActCnt   R-squared:                       0.277
Model:                            OLS   Adj. R-squared:                  0.276
Method:                 Least Squares   F-statistic:                     228.5
Date:                Fri, 25 Jun 2021   Prob (F-statistic):          1.06e-247
Time:                        05:26:41   Log-Likelihood:                -49971.
No. Observations:                3590   AIC:                         9.996e+04
Df Residuals:                    3583   BIC:                         1.000e+05
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       1.311e+05   1.23e+04     10.696      0.000    1.07e+05    1.55e+05
etc            -1.889e+05   1.05e+04    -18.059      0.000   -2.09e+05   -1.68e+05
days              91.1335      9.270      9.831      0.000      72.959     109.308
TxTfrValAdjUSD  9.929e-08   2.53e-06      0.039      0.969   -4.85e-06    5.05e-06
FeeMedUSD      -2.461e+04   5818.786     -4.230      0.000    -3.6e+04   -1.32e+04
RevUSD             0.0104      0.001      8.304      0.000       0.008       0.013
GasLmtTxMean       0.2659      0.034      7.897      0.000       0.200       0.332
==============================================================================
Omnibus:                     6951.550   Durbin-Watson:                   0.587
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         13412660.317
Skew:                          15.085   Prob(JB):                         0.00
Kurtosis:                     300.920   Cond. No.                     1.06e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.06e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
results = smf.ols('AdrActCnt ~ 1+ etc +days +etc*days+TxTfrValAdjUSD+FeeMedUSD+RevUSD+GasLmtTxMean', data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              AdrActCnt   R-squared:                       0.289
Model:                            OLS   Adj. R-squared:                  0.288
Method:                 Least Squares   F-statistic:                     208.4
Date:                Fri, 25 Jun 2021   Prob (F-statistic):          3.29e-260
Time:                        05:26:41   Log-Likelihood:                -49940.
No. Observations:                3590   AIC:                         9.990e+04
Df Residuals:                    3582   BIC:                         9.994e+04
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       6.736e+04   1.45e+04      4.637      0.000    3.89e+04    9.58e+04
etc            -6.579e+04   1.86e+04     -3.545      0.000   -1.02e+05   -2.94e+04
days             174.2124     13.873     12.558      0.000     147.013     201.411
etc:days        -146.8444     18.369     -7.994      0.000    -182.859    -110.830
TxTfrValAdjUSD -8.195e-07   2.51e-06     -0.327      0.744   -5.73e-06     4.1e-06
FeeMedUSD      -2.948e+04   5800.431     -5.083      0.000   -4.09e+04   -1.81e+04
RevUSD             0.0101      0.001      8.181      0.000       0.008       0.013
GasLmtTxMean       0.2540      0.033      7.604      0.000       0.189       0.320
==============================================================================
Omnibus:                     7092.343   Durbin-Watson:                   0.596
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         14921577.261
Skew:                          15.766   Prob(JB):                         0.00
Kurtosis:                     317.261   Cond. No.                     1.64e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.64e+10. This might indicate that there are
strong multicollinearity or other numerical problems.